// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace HealthGraphNet.Samples.Web {
	
	
	public partial class _Default {
		
		protected System.Web.UI.WebControls.Content HeaderContent;
		
		protected System.Web.UI.WebControls.Content BodyContent;
		
		protected System.Web.UI.HtmlControls.HtmlAnchor AAuthAnchor;
		
		protected System.Web.UI.WebControls.Panel PnlTokenSamples;
		
		protected System.Web.UI.WebControls.Label LblAccessType;
		
		protected System.Web.UI.WebControls.Label LblAccessToken;
		
		protected System.Web.UI.WebControls.Label LblUserId;
		
		protected System.Web.UI.WebControls.Label LblUserStrengthTrainingActivities;
		
		protected System.Web.UI.WebControls.Label LblUserWeight;
		
		protected System.Web.UI.WebControls.Label LblUserSettings;
		
		protected System.Web.UI.WebControls.Label LblUserDiabetes;
		
		protected System.Web.UI.WebControls.Label LblUserTeam;
		
		protected System.Web.UI.WebControls.Label LblUserSleep;
		
		protected System.Web.UI.WebControls.Label LblUserFitnessActivities;
		
		protected System.Web.UI.WebControls.Label LblUserNutrition;
		
		protected System.Web.UI.WebControls.Label LblUserGeneralMeasurements;
		
		protected System.Web.UI.WebControls.Label LblUserBackgroundActivities;
		
		protected System.Web.UI.WebControls.Label LblUserRecords;
		
		protected System.Web.UI.WebControls.Label LblUserProfile;
		
		protected System.Web.UI.WebControls.Label LblProfileName;
		
		protected System.Web.UI.WebControls.Label LblProfileLocation;
		
		protected System.Web.UI.WebControls.Label LblProfileAthleteType;
		
		protected System.Web.UI.WebControls.Label LblProfileGender;
		
		protected System.Web.UI.WebControls.Label LblProfileBirthday;
		
		protected System.Web.UI.WebControls.Label LblProfileElite;
		
		protected System.Web.UI.WebControls.Label LblProfileProfile;
		
		protected System.Web.UI.WebControls.Label LblProfileSmallPicture;
		
		protected System.Web.UI.WebControls.Label LblProfileNormalPicture;
		
		protected System.Web.UI.WebControls.Label LblProfileMediumPicture;
		
		protected System.Web.UI.WebControls.Label LblProfileLargePicture;
	}
}
